#!/bin/bash
clear

#-- colors v2 --#
R='\e[31;1m' #RED
G='\e[32;1m' #GREEN
Y='\e[33;1m' #YELLOW
DB='\e[34;1m' #DARKBLUE
P='\e[35;1m' #PURPLE
LB='\e[36;1m' #LIGHTBLUE

#-- colors v3 --#
BR='\e[3;31m' #RED
BG='\e[3;32m' #GREEN
BY='\e[3;33m' #YELLOW
BDB='\e[3;34m' #DARKBLUE
BP='\e[3;35m' #PURPLE
BLB='\e[3;36m' #LIGHTBLUE

clear
echo -e "$DB ************************************************"
echo -e "$DB *$G          auto fixer xderm-mini-gui           $DB*"
echo -e "$DB ************************************************"
echo -e "$LB"
echo -e "catatan : "
echo -e "fix xderm-mini-gui Download php"
echo -e "jika berhasil maka akan keluar pesan xderm-mini-gui berhasil di fix"
echo -e "setelah itu device openwrt anda akan otomatis reboot"
sleep 5
echo -e "$G"
echo -e "jika setelah reboot dan masih Download php :"
echo -e "- hapus semua histori yang pernah dibuka di browser"
echo -e "- buka dengan tab samaran"
echo -e "- ganti dengan browser lain"
sleep 5
echo -e ""
echo -e ""
echo -e "$Y mengedit config uhttpd..."
sleep 3
echo -e ""
echo -e "$R"

cek=$(cat /etc/config/uhttpd)
if [[ $cek == *"uhttpd 'mai"* ]]; then
echo -e "xderm-mini-gui berhasil di fix"
sleep 1
sed -i "/config uhttpd 'main'/a list interpreter '.php=/usr/bin/php-cgi'" /etc/config/uhttpd
fi

cek=$(cat /etc/config/uhttpd)
if [[ $cek == *"uhttpd 'mai"* ]]; then
echo -e "xderm-mini-gui berhasil di fix"
sleep 1
sed -i "/config uhttpd 'main'/a option ubus_prefix '/ubus'" /etc/config/uhttpd
echo -e "rebooting..."
sleep 4
reboot
rm -rf /root/fix-xderm-mini-gui
exit
fi

cek=$(cat /etc/config/uhttpd)
if [[ $cek == *"uhttpd mai"* ]]; then
echo -e "xderm-mini-gui berhasil di fix"
sleep 1
sed -i "/config uhttpd main/a list interpreter '.php=/usr/bin/php-cgi'" /etc/config/uhttpd
sleep 1
fi

cek=$(cat /etc/config/uhttpd)
if [[ $cek == *"uhttpd mai"* ]]; then
echo -e "xderm-mini-gui berhasil di fix"
sleep 1
sed -i "/config uhttpd main/a option ubus_prefix '/ubus'" /etc/config/uhttpd
echo -e "rebooting..."
sleep 4
reboot
rm -rf /root/fix-xderm-mini-gui
exit
fi





